#!/bin/bash
set -euo pipefail

# Initialize chezmoi and apply dotfiles from GitHub repo
# Skips install since mise handles that via postCreateCommand
chezmoi init --apply git@github.com:AhsanRahat12/dotfiles.git

exit 0
